name: to test
on:
  push:
    branches:
      master
env:
  MY_NAME: "Mantra"
jobs:
test:
runs-on: ubuntu-latest
  steps:
    - name: test1
      run: echo hoge
      if: ( 'a' == 'a' )

    - name: test2
      run: echo hoge
      if: ( 'a' == 'b' )
    - name: test3
      run: echo hoge
      if: &gt;
        'a' == 'a'

    - name: test4
      run: echo hoge
      if: &gt;
        'a' == 'b'

    - name: test5
      run: echo hoge
      if: &gt;
        ${{ 'a' == 'a' }}

    - name: test6
      run: echo hoge
      if: &gt;
      ${{ 'a' == 'b' }}


  my_first_job:
    if: github.event == 'push'
    runs-on: ubuntu-latest
    needs: my_second_job
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: printing1
        run: echo "This is $MY_NAME
    
  my_second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2
      - name: printing2
        run: echo "Hello everyone"
        

