name: to test
on:
  push:
    branches:
      master
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2
  my_second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2
